# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9001b46755ae0d7ee1dd249655118d3cb3d4791bea8b9f7979aa6c52ae8dac83af3c2a3f2a6824ba615faf94797f0093aaa4456ac74f3a5dde9135596bcdbef2

test:
  secret_key_base: 1274519f4d3574eeab0cbae20f715160eafae892382c8a2e0ca2868ca2ca4bb79b5cbac474e84491887ddfbb449311847fea5bd981711a796ee4f3031bd851c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
